## CLASSICAL DYNAMICS SIMULATION

In [86]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.transforms as mtransforms

In [87]:
def generate_weights_random(N, w, h, sigma, seed):
    '''Generates a symmetric random weights array drawn from a normal distribution for a given seed'''
    rng = np.random.default_rng(seed)                    #  set random seed for reproduciblity
    W_assym = rng.normal(w/N, sigma/(N**(1/2)),(N, N))   #  get normal distributed weight matrix
    W = (W_assym+ W_assym.T)/2                           #  symmetrize the random matrix 
    H = rng.normal(h/N, sigma/(N**(1/2)),(N))            #  get normal distributed H
    return W , H


def get_W_from_H(N, w, h, sigma, seed):
    """Calculates the transition matrix for all state transition from the Hamiltonian"""
    W, H = generate_weights_random(N, w, h, sigma, seed) # get random parameters
    W_trans = np.zeros((2**N,2**N))                      # matrix to store all allowed transitions
    
    for s in np.ndindex((N, N)):
        s = np.array(s)

        for s_prime in np.ndindex((2, 2)):
            s_prime = np.array(s_prime)


            g = np.exp(-np.dot(s_prime,(H + W @ s)))                # obtain probabilities of flips


            W_trans[int(''.join(map(str, s)),2)][int(''.join(map(str, s_prime)),2)] = g          # convert base 2 state to base 10 and store transition probability 

    # NORMALIZE THE WHOLE THING AT THE END.
    return W_trans

In [121]:
def discrete_time_dynamics(N, w, h, sigma, seed, t_vals,):
    """
    Get transition matrix from parameters; use it to update dyamics
    """
    l = t_vals.shape[0]                             # amount of iterations
    s_vals = np.zeros((l,2))                        # array to store values
    W = get_W_from_H(N, w, h, sigma, seed)          # get transition matrix

    s = np.random.randint(N)                        # initialize spin state in base 10

    for i in range(l):          
        yolo  = 1                    

    if s == 0:
        g1 = 0         #
        g2 = W[s][s+1]
    elif s == 3:
        g1 = W[s][s-1]
        g2 = 0
    else:
        g1 = W[s][s-1]
        g2 = W[s][s+1]
        
        p = np.random.rand()
        if 0 < p < g1:                              # flip spin 1
            s[0] = 1 - s[0]
            
        if g1 < p < (g1+ g2):                       # flip spin 2
            s[1] = 1 - s[1]

        if (g1+g2) < p < 1:                         # no flip
            pass                        

    s_vals[i] = s                                 
    return s_vals

def generate_states(s_vals, t_vals):
    """Convert back to 0,1 formalism"""
    states = np.zeros(len(t_vals))
    for i in range(len(t_vals)):
        if s_vals[i][0] == 0 and s_vals[i][1] == 0:
            states[i] = 0

        if s_vals[i][0] == 0 and s_vals[i][1] == 1:
            states[i] = 1

        if s_vals[i][0] == 1 and s_vals[i][1] == 0:
            states[i] = 2

        if s_vals[i][0] == 1 and s_vals[i][1] == 1:
            states[i] = 3
            
    return states
        

In [122]:
def plot_dynamics(s_vals, t_vals):
    fig = plt.figure(figsize=(25, 6));                           #  make plots
    fig.suptitle("WHOOOO", fontsize=30, y = 1)
    trans = mtransforms.ScaledTranslation(-20/72, 7/72, fig.dpi_scale_trans)

    states = generate_states(s_vals,t_vals)
    s1s2 = s_vals[:,0] * s_vals[:,1]


    ax1 = fig.add_subplot(1, 2, 1)
    ax1.plot(t_vals,states)
    ax1.set_xlabel("time", fontsize=20)
    ax1.set_ylabel("states", fontsize=20)
    
    ax2 = fig.add_subplot(1, 2, 2)
    ax2.plot(t_vals,s_vals[:,0])
    ax2.plot(t_vals,s_vals[:,1])
    ax2.plot(t_vals,s1s2)
    ax2.set_xlabel("time", fontsize=20)
    ax2.set_ylabel("states", fontsize=20)

In [123]:
#PARAMETERS
N  = 2
w = 1
h = 1
sigma = 0.3
seed = 777

dt = 0.01  #discrete time steps of simulation
sim_time = 2 #time simulation should run
t_vals = np.arange(0,sim_time,dt)

In [124]:
print(W)

[[1.         0.67007421 0.53037843 0.35539291]
 [1.         0.56868606 0.36467315 0.20738454]
 [1.         0.46072401 0.38505106 0.17740227]
 [1.         0.39101239 0.26475018 0.1035206 ]]


In [125]:
s = discrete_time_dynamics(N, w, h, sigma, seed, t_vals,)
plot_dynamics(s,t_vals)

[[1.         0.67007421 0.53037843 0.35539291]
 [1.         0.56868606 0.36467315 0.20738454]
 [1.         0.46072401 0.38505106 0.17740227]
 [1.         0.39101239 0.26475018 0.1035206 ]]
(4, 4)


IndexError: index 3 is out of bounds for axis 0 with size 2

In [93]:
W = get_W_from_H(N, w, h, sigma, seed)          # get transition matrix
W[2][3]

0.17740226779330676

In [120]:
print(np.random.randint(2, size=(2,)))

[0 0]
